version: '3.8'

services:

    myjenkins-blueocean-full:
        image: myjenkins-blueocean:lts-jdk21-chrome-driver-full
        container_name: jenkins-blueocean-full
        restart: on-failure
        privileged: true
        environment:
            - DOCKER_HOST=tcp://docker:2376
            - DOCKER_CERT_PATH=/certs/client
            - DOCKER_TLS_VERIFY=1
        ports:
            - 8093:8080
            - 50001:50000
#        volumes:
#            - ./jenkins-data:/var/jenkins_home
#            - ./jenkins-docker-certs:/certs/client:ro
        networks:
            - jenkins

networks:
    jenkins:
        external: true
