version: '3.8'

services:

    myjenkins-blueocean:
        image: myjenkins-blueocean:lts-jdk21
#        image: myjenkins-blueocean:lts-jdk21-chrome-driver
        container_name: jenkins-blueocean
        restart: on-failure
        privileged: true
        environment:
            - DOCKER_HOST=tcp://docker:2376
            - DOCKER_CERT_PATH=/certs/client
            - DOCKER_TLS_VERIFY=1
        ports:
            - 8092:8080
            - 50000:50000
        volumes:
            - ./jenkins-data:/var/jenkins_home
            - ./jenkins-docker-certs:/certs/client:ro
        networks:
            - jenkins

networks:
    jenkins:
        external: true
